{{- if eq .Values.mode "gateway" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zeroTouch.fullname" . }}
  labels:
{{ include "zeroTouch.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "zeroTouch.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "zeroTouch.labels" . | indent 8 }}
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config=/etc/otel/otel-collector-config.yaml"]
          ports:
            - containerPort: {{ .Values.service.ports.grpc }}
            - containerPort: {{ .Values.service.ports.http }}
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: otel-config
          configMap:
            name: {{ include "zeroTouch.fullname" . }}-config
{{- end }}
