{{- if eq .Values.mode "sidecar" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-sidecar-config
  labels:
{{ include "zeroTouch.labels" . | indent 4 }}
data:
  otel-collector-config.yaml: |
{{ include "zeroTouch.collectorConfig" . | indent 4 }}
{{- end }}
