apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instrumentations.opentelemetry.io
spec:
  group: opentelemetry.io
  scope: Namespaced
  names:
    plural: instrumentations
    singular: instrumentation
    kind: Instrumentation
    shortNames:
      - otelinst
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
